require motion-cocoapods
Because `rake pod:install’ cause an error even if setup this following README.

```
$ rake pod:install
rake aborted!
NoMethodError: undefined method `pods' for #<Motion::Project::IOSConfig:0x007fbf30c27260>
…
```